### ISSUE TITLE
Polybar

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso-Skel#20]
investigate possibilities - include for Obiwan Kenobi?
https://github.com/jaagr/polybar

**Comment by Dobbie03** [comment]
I would like to see Polybar included.  I love Polybar.

Maybe as the default panel for the i3wm

**Comment by erikdubois** [comment]
we can include it but as default panel.
the one I choose now is one for stability.
no issues after years
i will take the polybar-git

can you provide the codes to add to the config 

That is going to be option 4 to have a panel.

**Comment by erikdubois** [comment]
or ... postpone to Obi-Wan-Kenobi 
we need to come up with somthing then as well

**Comment by erikdubois** [comment]
it will be on the iso of R2-D2 - config lines can be done later

**Comment by Dobbie03** [comment]
Implemented as default in Minimo
