### ISSUE TITLE
LUKS+encryption fails

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-Iso-Skel#30]
Josh Sabboth hit me up on Hangouts to let me know that LUKS+encryption fails.

Snippets of his reply

> BTW I tested the luks+encryption on ArchLabs and it failed on two machines
> Grub points to the wrong drive label
> It is the correct device but it renames it to a string that isnt detectable
> I tried it with the last two releases
> It will says UUID...... (wrong label)
> The luks+encryption is the only time that happens

Not sure where to head with this

**Comment by natemaia** [comment]
We can look here for info on LUKS setup in calamares
https://github.com/calamares/calamares/wiki/LUKS-Deployment

**Comment by Dobbie03** [comment]
Can I leave this in your capable hands then?

**Comment by Dobbie03** [comment]
I did a fresh install on a legacy grub laptop, Josh did his on a UEFI.  My install was flawless.

**Comment by natemaia** [comment]
So the above packages are all that was needed for it to work properly?

If so I will add them to the package list

**Comment by Dobbie03** [comment]
I didn't add any extra packages, I just selected encryption in Calamares.

**Comment by natemaia** [comment]
So I am confused.. where is the issue then?

**Comment by Dobbie03** [comment]
I think it lays with UEFI laptops/PC's.  My laptop is legacy and Josh's is UEFI.

Can anyone test my theory?

**Comment by natemaia** [comment]
I still believe its the packages above that are needed for a proper full disk encryption under UEFI..

Can you ask Josh if I build him an iso with them on it would he test for me?

**Comment by Dobbie03** [comment]
Just waiting on a reply.

**Comment by Dobbie03** [comment]
Fixed.  See blog post regarding Minimo
