### ISSUE TITLE
Broadcom Drivers

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-Iso-Skel#31]
Brett aka @toola69 just sent me a message to say he is getting asked about broadcom drivers.  We will need to include them in +6

**Comment by natemaia** [comment]
We already include broadcom-wl 

Are we sure they are using 5.0 or is this just an outdated issue

**Comment by Dobbie03** [comment]
I know on my test craptop I had to install further broadcom drivers for the wifi to work.

This was using the latest version.

**Comment by natemaia** [comment]
Do you remember what package you installed, there isn't much in the official repos so we'd have to package it

**Comment by natemaia** [comment]
there is alot of broadcom stuff on the AUR so it wouldnt be too hard, just which ones do we need/want

**Comment by Dobbie03** [comment]
Let me scroll through my terminal on my craptop and I will come back to you.

**Comment by natemaia** [comment]
was it something along the lines of b43-firmware?

**Comment by Dobbie03** [comment]
Fixed with Minimo.

**Comment by subgitlab** [comment]
As far as I tried archlabs in Hardware acer 5743
Network controller: Broadcom Limited BCM43225

archlabs-2018.06.iso without drivers
archlabs-2018.05.1.iso without drivers

archlabs-2018.05.iso got drivers

Therefore in latest iso broadcom drivers are missing

## Thanks for viewing and solving :grinning:
