### ISSUE TITLE
al-obthemes missing components

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-Iso-Skel#32]
al-obthemes requires al-xinerama-prop, needs to be added to the ISO

https://drive.google.com/file/d/0B1F9Pr3ojH9pM3ZuaWx0MUJnQUU/view?usp=sharing

**Comment by Dobbie03** [comment]
Adding this brings a whole lot more in the way of issues:

`Traceback (most recent call last):
  File "/usr/bin/al-xinerama-prop", line 20, in <module>
    import pygtk
ModuleNotFoundError: No module named 'pygtk'
al-obthemes: line 262: / 3 : syntax error: operand expected (error token is "/ 3 ")
`

pygtk is included but is not importing.

**Comment by Dobbie03** [comment]
Upon further reading, it appears pygtk is python2 only,

https://bbs.archlinux.org/viewtopic.php?id=224540

**Comment by Dobbie03** [comment]
After further duscussion with @natemaia I vote for removal of this.  Does anyone actually use it?

I think we should post a poll at Google+ closer to the next release date asking who uses and who doesn't.

**Comment by natemaia** [comment]
That sounds like a good idea, see if people want it at all

**Comment by Dobbie03** [comment]
Closed.
