### ISSUE TITLE
Proposed changes for +6

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-Iso-Skel#35]
Okay lets make this entry the talking point for +6.
@erikdubois @natemaia 
Some changes I would like to see:

-A new default wallpaper, see here:
JPG: https://scrot.moe/image/6y0la
PNG: https://scrot.moe/image/6y1QN
Possibly a few variations of this
- A new conky, up for debate
- Firefox as the ONE and only browser
- A reduction in themes, too many choices with only minor differences between them all.
- A new default icon theme.
- A light theme as the default that isn't Arc.
- Polybar as default panel.  Need a nice unique ArchLabs theme.

A list of applications for possible removal is here:
https://docs.google.com/document/d/1NkA9gyI2ZZJn8RifwmRc3eurzRbkVBB4kt1hHLYpdNk/edit?usp=sharing
Add what you think we don't need so we can evaluate.

**Comment by Dobbie03** [comment]
Possible default conky could be a modified AL version of:
http://fav.me/dbfyxtm

**Comment by Dobbie03** [comment]
Or this, which is a mod of my original anyway
http://fav.me/dbfj8rn

**Comment by natemaia** [comment]
I am all for this, it would give us more appeal with the users that want a slimmer distro and those who want to customise more than anything. 

Simplifying things a little and carving out our own style, while still being familiar would give us the best appeal across the board.

Most users fall in one of two groups 

1 - They don't care about tweaking stuff or looks, they just want it to work, get the software they use, and do what they need 

2 - They love tweaking things and changing it up, which likely will install or make their own to suit their tastes

Given we are using lightweight WM's and not full DE's I think we need a solid idea of who our target audience is, this should make choices like this easier in the future.

**Comment by Dobbie03** [comment]
I'd also like to see a vote on G+ for our next release name too.  Star Wars orientated of course.

**Comment by Dobbie03** [comment]
No longer required.
