### ISSUE TITLE
standard conky gets blurred if openbox restarts

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso-Skel#6]
conky: Syntax error (/home/erik/.conkyrc:2: unexpected symbol near '#') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: desktop window (3b5) is root window
conky: window type - normal
conky: drawing to created window (0x1400001)
conky: drawing to double buffer
conky: forked to background, pid is 1220

checkout - new syntax ?

**Comment by Dobbie03** [comment]
This sounds like an issue with the new Syntax.  Here is a link to the old syntax Conky, might be an idea to replace the new syntax for testing?

https://drive.google.com/file/d/0B1F9Pr3ojH9pUVF5enJWaTI1Qnc/view?usp=sharing

**Comment by erikdubois** [comment]
i have changed the code in the meantime
tried to find why the conky gets blurred if you restart openbox ctrl+shift+backspace
every second he puts on a new conky - that makes it blur
aureola conky does not have that
we will compare notes in future.

**Comment by erikdubois** [comment]
To all users: 
WE ADVISE USERS TO USE THE MENU 
preferences/openbox/reconfigure instead of restart
or
reload the conky

**Comment by erikdubois** [comment]
we changed the keyboard shortcut to --reconfigure instead of restart

**Comment by erikdubois** [comment]
closing for now
